# Generated by Django 6.0.3 on 2026-05-17 08:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the doctor.', max_length=100)),
                ('specialization', models.CharField(help_text='Specialization of the doctor (e.g., Cardiologist).', max_length=100)),
                ('experience_years', models.PositiveIntegerField(help_text='Years of clinical experience.', validators=[django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(help_text='Email address of the doctor (must be unique).', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('clinic_address', models.TextField(blank=True, help_text='Physical address of the clinic.', null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, help_text='Consultation fee per visit.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this doctor profile is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
