# Generated by Django 4.2 on 2026-04-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP'), ('Javascript', 'Javascript'), ('Others', 'Others')], default='Others', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='notes_files/'),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
