# Generated by Django 4.2 on 2026-04-29 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_note_category_note_file_upload_note_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
