# Generated by Django 4.2 on 2026-04-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
