# Generated by Django 4.2 on 2026-04-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_contactmessage_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
