# Generated by Django 6.0.3 on 2026-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_genre_mediaitem_backdrop_mediaitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='tmdb_backdrop_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='tmdb_poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
