# Generated by Django 6.0.3 on 2026-05-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mediaitem_tmdb_backdrop_path_mediaitem_tmdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='rt_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
